### ISSUE TITLE
兄弟,我没看见你做sign签名和verify两个地方

### ISSUE THREAD

**Issue by junmaqiang** [lscho/ThinkJS-Vue.js-blog#1]
下面是我用thinkjs框架中src/config/adapter.ts里面的配置代码
```js
  jwt: {
    handle: JWTSession,
    secret: 'rongyi',  // 相当于服务端秘钥
    tokenType: 'header', // Token传递方式 ['query', 'body', 'header', 'cookie'], 'cookie' is default
    tokenName: 'authorization', // if tokenType not 'cookie', this will be token name, 'jwt' is default
    sign: {},
    verify: {}
  }
```
我发现sign和verify两个都是空的,请问如果没有这两个地方的使用, jwt 的意义就不大了吧?

**Comment by junmaqiang** [comment]
要想验证token里面的有效期, 看了你的例子确实找不出你是如何做的!

**Comment by lscho** [comment]
[https://github.com/thinkjs/think-session-jwt/blob/master/index.js#L61](https://github.com/thinkjs/think-session-jwt/blob/master/index.js#L61)  autoSave生成签名，[https://github.com/thinkjs/think-session-jwt/blob/master/index.js#L27](https://github.com/thinkjs/think-session-jwt/blob/master/index.js#L27)initSessionData方法里进行了验证

**Comment by junmaqiang** [comment]
感谢 @lscho 的 回答
我通过参数配置,达到了我有效期的控制,代码如下:
```js
  jwt: {
    handle: JWTSession,
    secret: 'rong-he',  // 相当于服务端秘钥
    tokenType: 'header', // Token传递方式 ['query', 'body', 'header', 'cookie'], 'cookie' is default
    tokenName: 'authorization', // if tokenType not 'cookie', this will be token name, 'jwt' is default
    sign: {// 签署1分钟期限(60*10)的token
      expiresIn: 60 * 10
    },
    verify: {}
  }
```

还有个问题, 是不是意味着 我的有效期是动态变更的?

**Comment by lscho** [comment]
是的，如果配置了有效期，超过有效期的话就自动失效了
