### ISSUE TITLE
hook

### ISSUE THREAD

**Issue by calvinCar** [lscho/ThinkJS-Vue.js-blog#10]
extent hook的功能是什么呀，一直不太懂

**Comment by lscho** [comment]
其实就是想实现一个简单的插件机制，hook其实就是插件点，一般都称为“钩子”，php的程序里用的比较多。

大概功能就是程序运行到这里的时候，就去检测这个插件点有哪些插件可以调用，然后去执行。所以，我们的插件只要合乎规范，就可以对留有插件点的地方进行无缝扩展。

**Comment by calvinCar** [comment]
我发现a链接hover的 时候也会去请求数据，然后查询数据库，怎么样能让他hover的时候不去请求数据呢，不然的话这个阅读量就有点不准确了，我鼠标悬停，阅读量就会加1了

**Comment by lscho** [comment]
因为使用了 instantclick 无刷新预加载库，默认是hover悬停后就加载，提高响应速度。可以修改 https://github.com/lscho/ThinkJS-Vue.js-blog/blob/master/view/footer.html#L50 为`InstantClick.init('mousedown')` 这样就是鼠标点击后加载了。

**Comment by calvinCar** [comment]
感谢感谢，我还想着要不做成前端domReady之后去发送ajax请求呢 哈哈，谢谢啦QAQ

**Comment by lscho** [comment]
点个star吧

**Comment by calvinCar** [comment]
不过我试了，点击一次之后还是会发送两次请求，文章的阅读量还是不能正确的统计出来，不知道大大您有什么好的想法嘛

**Comment by lscho** [comment]
稍后我测试一下给你回复

**Comment by lscho** [comment]
好的
