### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by NLxs** [lscho/ThinkJS-Vue.js-blog#18]
你好！我在github上看到了您的项目，有一些安装部署的问题遇到了一些问题，先您请教一下，我现在admin目录下npm install 然后在adapter.js 和adapter.production.js修改了一下修改了mysql的相对应的信息，然后又在mysql中创建了新的数据库blog然后将database.sql导入，这写我做完以后，在admin目录和外面的目录先本别npm start 但是项目无法正常启动，麻烦您讲一下部署目录的正确方法！

**Comment by lscho** [comment]
在项目目录和admin下分别执行npm install。。无法正常启动控制台报什么错？

**Comment by NLxs** [comment]
前台现在可以启动了，后台启动后显示这个Cannot GET /，在admin  npm install 后Downloading https://chromedriver.storage.googleapis.com/2.42/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip   后台启动后在控制台显示的错误也和这个有关系

**Comment by lscho** [comment]
使用cnpm安装一下试试

**Comment by NLxs** [comment]
ERROR  Failed to compile with 4 errors                                13:17:12

 error  in ./src/view/Main.vue

Syntax Error: Unexpected token (140:4)

  138 |       return arr;
  139 |     },
> 140 |     ...mapState({
      |     ^
  141 |       route: state => state.route
  142 |     })
  143 |   },

还有这个错误是什么原因？
应该不是npm的原因我这边网络还是可以的

**Comment by lscho** [comment]
语法不支持。。你的nodejs版本多少

**Comment by lscho** [comment]
应该是babel的某个组件没有安装好。。。你检查一下npm install过程中有没有什么问题
