### ISSUE TITLE
数据库导入报错

### ISSUE THREAD

**Issue by jiazehua** [lscho/ThinkJS-Vue.js-blog#4]
[Err] 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `ls_meta` (
  `id` int(10) NOT NULL,
  `uid` int(10) NOT NULL,
 ' at line 21

**Comment by lscho** [comment]
不好意思，电脑关了，明天看一下给你回复。

**Comment by lscho** [comment]
更新了，后台默认账号密码 root  123456，有一些文章数据直接删掉就可以
